version: '3.8'

services:

  db:
    image: postgres:14
    restart: always
    container_name: postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=adminAuto
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=automanager

  admin_db:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: automanager123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "80:80"
    depends_on:
      - db

  web:
    build: .
    container_name: django
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=automanager
      - POSTGRES_USER=adminAuto
      - POSTGRES_PASSWORD=12345678
    depends_on:
      - db
    